<?php
session_start();
date_default_timezone_set('Australia/Melbourne');
?>
<!DOCTYPE html>
	<head>
		<title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="css/style.css">
		<link rel="stylesheet" type="text/css" href="css/bookingStyle.css">
		<link rel="stylesheet" type="text/css" href="css/mobile.css">
		<link href='http://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="css/bookingMobile.css">
    <link rel="stylesheet" href="css/pikaday.css">
    <script src ="js/jquery-1.5.2.js"></script>
    
	</head>
	<body class="div03 stretchMe" data-stretch="images/background-yellow.jpg">
			<nav class="top-header navbar navbar-default" role="navigation">
         <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              
              <div class="logo">
								<a href="index.html">Taxi2 <span>MelAirport</span></a>
					  </div>
              
            </div>
            <div class="top-header"> 
						<div class="wrap">
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
								<div class="top-nav nav navbar-nav">
									<ul>
										<li ><a href="index.html" class="scroll">Home</a></li>
										<li><a href="about.html" class="scroll">About</a></li>
										<li><a href="fleet.html" class="scroll">Our Fleet</a></li>
										<li><a href="fareEstimator.html" class="scroll">Fare Estimator</a></li>
										<li class="active"><a  href="booking.php" class="scroll">Booking</a></li>	
									</ul>
								</div>
								<div class="clear"> </div>
							</div>
						</div>
					</div>
         </div><!-- /.container-fluid -->
     </nav>
      <div class="row">
         <div class="col-sm-8">
          <form role="form" style="margin-top:10px;" class="form-inline" action="bookingValidation.php" method="POST">
            <div class="row flashMessage">
              <?php
               if (!empty($_SESSION['flash_message']))
                {
                  echo $_SESSION['flash_message'];
                  unset($_SESSION['flash_message']);
                }
              ?>
            </div>
              <div class="row flashMessage" style="color:green">
              <?php
              if (!empty($_SESSION['flash_message1']))
                {
                  echo $_SESSION['flash_message1'];
                  unset($_SESSION['flash_message1']);
                }
              ?>
            </div>
        <div class="row">
          <div class="col-sm-12 " ><p >Personnal Details</p></div>
          <div class="form-group col-sm-6" >
             

            <h3><input type="text" name="name" class="form-control" placeholder="Full Name " value = "<?php if(isset($_SESSION['name'])) echo $_SESSION['name']; ?>"></h3>
          
        </div>

           <div class="form-group col-sm-offset-1 col-sm-5" >
            <h3><input type="email" name="email" class="form-control" placeholder="Enter Email" value = "<?php if(isset($_SESSION['email'])) echo $_SESSION['email']; ?>"></h3>
          </div>
        </div>
        <div class="row">
          
          <div class="form-group col-sm-6" >
             <h3><input type="text" name="phone" class="form-control" placeholder="Enter Phone Number" value = "<?php if(isset($_SESSION['phone'])) echo $_SESSION['phone']; ?>"></h3>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12"><p>Pick Up Details</p></div>
          <div id="datetimepicker" class="form-group col-sm-6" >
            <h3><input type="date" class="form-control " name="date" placeholder="Please specify a date"   value = "<?php if(isset($_SESSION['date'])) echo $_SESSION['date']; else echo date('Y-m-d');?>"></h3>
          </div>
          <div class="form-group col-sm-offset-1 col-sm-5" >
            <h3><input type="time" name="time" class="form-control dateclass placeholderclass"   value = "<?php if(isset($_SESSION['time'])) echo $_SESSION['time']; else echo date('h:m');?>"></h3>
          </div>
        </div>
        <div class="row">
          
          <div class="form-group col-sm-6" >
            <div class="form-group col-sm-6" style="padding-left:0px">
              <h3><select name="persons" class="form-control" value = "<?php if(isset($_SESSION['persons'])) echo $_SESSION['persons']; ?>">
              <option value="">No of Passengers</option>
              <option value = "1">1</option>
              <option value = "2">2</option>
              <option value ="3">3</option>
              <option value = "4">4</option>
              <option value = "5">5</option>
              <option value = "6">6</option>
              <option value = "7">7</option>
              <option value = "8">8</option>
              <option value = "9">9</option>
            </select></h3>
              
            </div>
            <div class="form-group col-sm-6 briefcase" style="padding-right:0px">
              <h3><input type="text" name="bNo" class="form-control" placeholder="No. of Briefcase (OPTIONAL)"></h3>
            </div>
          </div>
          <div class="form-group col-sm-offset-1 col-sm-5" >
            <h3><select name="car" class="form-control" value = "<?php if(isset($_SESSION['car'])) echo $_SESSION['car']; ?>">
              <option value="">Select Type of Car</option>
              <option value = "Silver Service">Silver Service</option>
              <option value = "Normal Sedan">Normal Sedan</option>
              <option value ="Wagon">Wagon</option>
              <option value = "Maxi">Maxi</option>
            </select></h3>
          </div>
        </div>
        <div class="row">

          <div class="form-group col-sm-6" style="padding-left:0px; padding-right:0px" >
            <div class="form-group col-sm-3">
              <input type="text" name="pUnit" class="form-control" placeholder="Unit/Flat No" value = "<?php if(isset($_SESSION['pUnit'])) echo $_SESSION['pUnit']; ?>"></h3>
            </div>
             <div class="form-group col-sm-offset-1 col-sm-7" style="padding-right:0px">
               <h3><input type="text" name="pAddress" class="form-control" placeholder="Street Name" value = "<?php if(isset($_SESSION['pAddress'])) echo $_SESSION['pAddress']; ?>"></h3>
             </div>
          </div>
          <div class="form-group col-sm-offset-1 col-sm-5" >
            <h3><select  class="form-control" onchange="document.getElementById('text_content').value=this.options[this.selectedIndex].text"  ></h3>
        <option value="">Please Select Suburb</option>
        <option value="Abbotsford" >Abbotsford</option>
        <option value="Aberfeldie" >Aberfeldie</option>
        <option value="Adams Estate" >Adams Estate</option>
        <option value="Aireys Inlet" >Aireys Inlet</option>
        <option value="Airport West" >Airport West</option>
        <option value="Albanvale" >Albanvale</option>
        <option value="7" >Albert Park</option>
        <option value="8" >Albion</option>
        <option value="9" >Almurta</option>
        <option value="10" >Alphington</option>
        <option value="11" >Altona</option>
        <option value="12" >Altona Meadows</option>
        <option value="13" >Altona North</option>
        <option value="14" >Anakie</option>
        <option value="15" >Anderson</option>
        <option value="16" >Anglesea</option>
        <option value="17" >Archies Creek</option>
        <option value="18" >Ardeer</option>
        <option value="19" >Armadale</option>
        <option value="20" >Arthurs Creek</option>
        <option value="21" >Arthurs Seat</option>
        <option value="1056" >As Directed</option>
        <option value="22" >Ascot Vale</option>
        <option value="23" >Ashbourne</option>
        <option value="24" >Ashburton</option>
        <option value="25" >Ashwood</option>
        <option value="26" >Aspendale</option>
        <option value="27" >Aspendale Gardens</option>
        <option value="28" >Athlone</option>
        <option value="29" >Attwood</option>
        <option value="30" >Avalon</option>
        <option value="31" >Avondale Heights</option>
        <option value="32" >Avonsleigh</option>
        <option value="33" >Bacchus Marsh</option>
        <option value="34" >Badger Creek</option>
        <option value="35" >Balaclava</option>
        <option value="36" >Ballan</option>
        <option value="37" >Balliang</option>
        <option value="38" >Balliang East</option>
        <option value="39" >Balnarring</option>
        <option value="40" >Balnarring Beach</option>
        <option value="41" >Balwyn</option>
        <option value="42" >Balwyn North</option>
        <option value="43" >Bambra</option>
        <option value="44" >Bamganie</option>
        <option value="45" >Bangholme</option>
        <option value="46" >Bannockburn</option>
        <option value="47" >Barkstead</option>
        <option value="48" >Barrabool</option>
        <option value="49" >Barrys Reef</option>
        <option value="50" >Barwon Heads</option>
        <option value="51" >Bass</option>
        <option value="52" >Batesford</option>
        <option value="53" >Baxter</option>
        <option value="54" >Bayles</option>
        <option value="55" >Bayswater</option>
        <option value="56" >Bayswater North</option>
        <option value="57" >Beaconsfield</option>
        <option value="58" >Beaconsfield Upper</option>
        <option value="59" >Beaumaris</option>
        <option value="60" >Beenak</option>
        <option value="61" >Belgrave</option>
        <option value="62" >Belgrave Heights</option>
        <option value="63" >Belgrave South</option>
        <option value="64" >Bell Park</option>
        <option value="65" >Bell Post Hill</option>
        <option value="66" >Bellarine</option>
        <option value="67" >Bellbrae</option>
        <option value="68" >Bellfield</option>
        <option value="69" >Bellfield (Greater Melbourne)</option>
        <option value="70" >Bells Beach</option>
        <option value="71" >Belmont</option>
        <option value="72" >Bena</option>
        <option value="73" >Bend Of Islands</option>
        <option value="74" >Bentleigh</option>
        <option value="75" >Bentleigh East</option>
        <option value="76" >Beremboke</option>
        <option value="77" >Berwick</option>
        <option value="78" >Beveridge</option>
        <option value="79" >Big Hill</option>
        <option value="80" >Big Hill (Lorne)</option>
        <option value="81" >Big Pats Creek</option>
        <option value="82" >Bittern</option>
        <option value="83" >Black Rock</option>
        <option value="84" >Blackburn</option>
        <option value="85" >Blackburn North</option>
        <option value="86" >Blackburn South</option>
        <option value="87" >Blackwood</option>
        <option value="88" >Blairgowrie</option>
        <option value="89" >Blakeville</option>
        <option value="90" >Blampied</option>
        <option value="91" >Blind Bight</option>
        <option value="92" >Bolinda</option>
        <option value="93" >Bolwarrah</option>
        <option value="94" >Bonbeach</option>
        <option value="95" >Boneo</option>
        <option value="96" >Boonah</option>
        <option value="97" >Boronia</option>
        <option value="98" >Botanic Ridge</option>
        <option value="99" >Box Hill</option>
        <option value="100" >Box Hill North</option>
        <option value="101" >Box Hill South</option>
        <option value="102" >Braeside</option>
        <option value="103" >Braybrook</option>
        <option value="104" >Breakwater</option>
        <option value="105" >Breamlea</option>
        <option value="106" >Briar Hill</option>
        <option value="107" >Brighton</option>
        <option value="108" >Brighton East</option>
        <option value="109" >Broadmeadows</option>
        <option value="110" >Brookfield</option>
        <option value="111" >Brooklyn</option>
        <option value="113" >Brunswick</option>
        <option value="114" >Brunswick East</option>
        <option value="115" >Brunswick West</option>
        <option value="116" >Buckley</option>
        <option value="117" >Bulla</option>
        <option value="118" >Bullarook</option>
        <option value="119" >Bullarto</option>
        <option value="120" >Bullarto South</option>
        <option value="121" >Bulleen</option>
        <option value="122" >Bullengarook</option>
        <option value="123" >Bunding</option>
        <option value="124" >Bundoora</option>
        <option value="125" >Bungal</option>
        <option value="126" >Bungaree</option>
        <option value="127" >Bunyip</option>
        <option value="128" >Bunyip North</option>
        <option value="129" >Burnley</option>
        <option value="130" >Burnside</option>
        <option value="131" >Burnside Heights</option>
        <option value="132" >Burwood</option>
        <option value="133" >Burwood East</option>
        <option value="134" >Buxton</option>
        <option value="135" >Bylands</option>
        <option value="136" >Cairnlea</option>
        <option value="137" >Calder Park</option>
        <option value="138" >Caldermeade</option>
        <option value="139" >Camberwell</option>
        <option value="140" >Campbellfield</option>
        <option value="141" >Cannons Creek</option>
        <option value="142" >Canterbury</option>
        <option value="143" >Cape Schanck</option>
        <option value="144" >Cape Woolamai</option>
        <option value="145" >Cardinia</option>
        <option value="146" >Carlton</option>
        <option value="147" >Carlton North</option>
        <option value="148" >Carnegie</option>
        <option value="149" >Caroline Springs</option>
        <option value="150" >Carrum</option>
        <option value="151" >Carrum Downs</option>
        <option value="152" >Castella</option>
        <option value="153" >Catani</option>
        <option value="154" >Caulfield</option>
        <option value="155" >Caulfield East</option>
        <option value="156" >Caulfield North</option>
        <option value="157" >Caulfield South</option>
        <option value="158" >Ceres</option>
        <option value="159" >Chadstone</option>
        <option value="1076" >Charlton</option>
        <option value="161" >Chelsea</option>
        <option value="162" >Chelsea Heights</option>
        <option value="163" >Cheltenham</option>
        <option value="164" >Cherokee</option>
        <option value="165" >Chintin</option>
        <option value="166" >Chirnside Park</option>
        <option value="167" >Christmas Hills</option>
        <option value="168" >Chum Creek</option>
        <option value="823" >City</option>
        <option value="1075" >City Special</option>
        <option value="170" >Claretown</option>
        <option value="171" >Clarinda</option>
        <option value="172" >Clarkefield</option>
        <option value="173" >Clayton</option>
        <option value="174" >Clayton South</option>
        <option value="175" >Clematis</option>
        <option value="176" >Clifton Hill</option>
        <option value="177" >Clifton Springs</option>
        <option value="178" >Clonbinane</option>
        <option value="179" >Clyde</option>
        <option value="180" >Clyde North</option>
        <option value="181" >Coburg</option>
        <option value="182" >Coburg North</option>
        <option value="183" >Cockatoo</option>
        <option value="184" >Cocoroc</option>
        <option value="185" >Coimadai</option>
        <option value="186" >Colbrook</option>
        <option value="187" >Coldstream</option>
        <option value="188" >Collingwood</option>
        <option value="189" >Connewarre</option>
        <option value="190" >Coolaroo</option>
        <option value="191" >Cora Lynn</option>
        <option value="192" >Corinella</option>
        <option value="193" >Corio</option>
        <option value="194" >Coronet Bay</option>
        <option value="195" >Cottles Bridge</option>
        <option value="196" >Cowes</option>
        <option value="197" >Craigieburn</option>
        <option value="198" >Cranbourne</option>
        <option value="199" >Cranbourne East</option>
        <option value="200" >Cranbourne North</option>
        <option value="201" >Cranbourne South</option>
        <option value="202" >Cranbourne West</option>
        <option value="203" >Cremorne</option>
        <option value="204" >Crib Point</option>
        <option value="205" >Croydon</option>
        <option value="206" >Croydon Hills</option>
        <option value="207" >Croydon North</option>
        <option value="208" >Croydon South</option>
        <option value="209" >Curlewis</option>
        <option value="210" >Dales Creek</option>
        <option value="211" >Dallas</option>
        <option value="212" >Dalmore</option>
        <option value="213" >Dalyston</option>
        <option value="214" >Dandenong</option>
        <option value="215" >Dandenong North</option>
        <option value="216" >Dandenong South</option>
        <option value="217" >Darley</option>
        <option value="218" >Darraweit Guim</option>
        <option value="219" >Daylesford</option>
        <option value="220" >Dean</option>
        <option value="1072" >Deepdene</option>
        <option value="221" >Deer Park</option>
        <option value="222" >Delahey</option>
        <option value="223" >Derrimut</option>
        <option value="224" >Devon Meadows</option>
        <option value="225" >Dewhurst</option>
        <option value="226" >Diamond Creek</option>
        <option value="227" >Diggers Rest</option>
        <option value="228" >Dingley Village</option>
        <option value="229" >Dixons Creek</option>
        <option value="230" >Docklands</option>
        <option value="231" >Don Valley</option>
        <option value="232" >Doncaster</option>
        <option value="233" >Doncaster East</option>
        <option value="234" >Donnybrook</option>
        <option value="235" >Donvale</option>
        <option value="236" >Doreen</option>
        <option value="237" >Doveton</option>
        <option value="238" >Dromana</option>
        <option value="239" >Drouin South</option>
        <option value="240" >Drumcondra</option>
        <option value="241" >Drysdale</option>
        <option value="243" >Durdidwarrah</option>
        <option value="244" >Eaglemont</option>
        <option value="245" >East Geelong</option>
        <option value="246" >East Melbourne</option>
        <option value="247" >East Warburton</option>
        <option value="248" >Eastern View</option>
        <option value="249" >Eden Park</option>
        <option value="250" >Edithvale</option>
        <option value="251" >Eganstown</option>
        <option value="252" >Elaine</option>
        <option value="253" >Elsternwick</option>
        <option value="254" >Eltham</option>
        <option value="255" >Eltham North</option>
        <option value="256" >Elwood</option>
        <option value="257" >Emerald</option>
        <option value="258" >Endeavour Hills</option>
        <option value="259" >Epping</option>
        <option value="829" >Epping North</option>
        <option value="260" >Essendon</option>
        <option value="261" >Essendon Fields</option>
        <option value="262" >Essendon North</option>
        <option value="263" >Essendon West</option>
        <option value="264" >Eumemmerring</option>
        <option value="265" >Exford</option>
        <option value="266" >Eynesbury</option>
        <option value="267" >Fairfield</option>
        <option value="268" >Fairhaven</option>
        <option value="269" >Fawkner</option>
        <option value="270" >Fern Hill</option>
        <option value="271" >Fernshaw</option>
        <option value="272" >Ferntree Gully</option>
        <option value="273" >Ferny Creek</option>
        <option value="274" >Fingal</option>
        <option value="275" >Fiskville</option>
        <option value="276" >Fitzroy</option>
        <option value="277" >Fitzroy North</option>
        <option value="278" >Flemington</option>
        <option value="279" >Flinders</option>
        <option value="280" >Flowerdale</option>
        <option value="281" >Footscray</option>
        <option value="282" >Forest Hill</option>
        <option value="283" >Frankston</option>
        <option value="284" >Frankston North</option>
        <option value="285" >Frankston South</option>
        <option value="286" >French Island</option>
        <option value="287" >Freshwater Creek</option>
        <option value="288" >Fyansford</option>
        <option value="289" >Gardenvale</option>
        <option value="290" >Garfield</option>
        <option value="291" >Garfield North</option>
        <option value="292" >Geelong</option>
        <option value="293" >Geelong West</option>
        <option value="294" >Gembrook</option>
        <option value="295" >Gentle Annie</option>
        <option value="296" >Gherang</option>
        <option value="297" >Gheringhap</option>
        <option value="298" >Gilderoy</option>
        <option value="299" >Gisborne</option>
        <option value="300" >Gisborne South</option>
        <option value="301" >Gladstone Park</option>
        <option value="302" >Gladysdale</option>
        <option value="303" >Glen Alvie</option>
        <option value="304" >Glen Forbes</option>
        <option value="305" >Glen Huntly</option>
        <option value="306" >Glen Iris</option>
        <option value="307" >Glen Waverley</option>
        <option value="308" >Glenburn</option>
        <option value="309" >Glenmore</option>
        <option value="310" >Glenroy</option>
        <option value="311" >Gnarwarre</option>
        <option value="312" >Gordon</option>
        <option value="313" >Gowanbrae</option>
        <option value="314" >Grantville</option>
        <option value="315" >Greendale</option>
        <option value="316" >Greensborough</option>
        <option value="317" >Greenvale</option>
        <option value="318" >Grovedale</option>
        <option value="319" >Gruyere</option>
        <option value="320" >Guys Hill</option>
        <option value="321" >Hadfield</option>
        <option value="322" >Hallam</option>
        <option value="323" >Hamlyn Heights</option>
        <option value="324" >Hampton</option>
        <option value="325" >Hampton East</option>
        <option value="326" >Hampton Park</option>
        <option value="328" >Harkaway</option>
        <option value="329" >Hastings</option>
        <option value="330" >Hawthorn</option>
        <option value="331" >Hawthorn East</option>
        <option value="332" >Hazeldene</option>
        <option value="333" >Healesville</option>
        <option value="334" >Heath Hill</option>
        <option value="335" >Heathcote Junction</option>
        <option value="336" >Heatherton</option>
        <option value="337" >Heathmont</option>
        <option value="338" >Heidelberg</option>
        <option value="339" >Heidelberg Heights</option>
        <option value="340" >Heidelberg West</option>
        <option value="341" >Herne Hill</option>
        <option value="342" >Hesket</option>
        <option value="344" >Highett</option>
        <option value="345" >Highton</option>
        <option value="346" >Hillside</option>
        <option value="347" >Hillside (Melton)</option>
        <option value="348" >Hmas Cerberus</option>
        <option value="349" >Hoddles Creek</option>
        <option value="350" >Hopetoun Park</option>
        <option value="351" >Hoppers Crossing</option>
        <option value="352" >Hughesdale</option>
        <option value="353" >Humevale</option>
        <option value="354" >Huntingdale</option>
        <option value="355" >Hurstbridge</option>
        <option value="356" >Indented Head</option>
        <option value="357" >Ingliston</option>
        <option value="358" >Inverleigh</option>
        <option value="359" >Inverloch</option>
        <option value="360" >Iona</option>
        <option value="361" >Ivanhoe</option>
        <option value="362" >Ivanhoe East</option>
        <option value="363" >Jacana</option>
        <option value="364" >Jam Jerrup</option>
        <option value="365" >Jan Juc</option>
        <option value="366" >Jeetho</option>
        <option value="368" >Jumbunna</option>
        <option value="369" >Junction Village</option>
        <option value="370" >Kalkallo</option>
        <option value="371" >Kallista</option>
        <option value="372" >Kalorama</option>
        <option value="1051" >Kananook</option>
        <option value="373" >Kangaroo Ground</option>
        <option value="374" >Kealba</option>
        <option value="375" >Keilor</option>
        <option value="376" >Keilor Downs</option>
        <option value="377" >Keilor East</option>
        <option value="378" >Keilor Lodge</option>
        <option value="379" >Keilor North</option>
        <option value="380" >Keilor Park</option>
        <option value="381" >Kensington</option>
        <option value="382" >Kernot</option>
        <option value="383" >Kerrie</option>
        <option value="384" >Kew</option>
        <option value="385" >Kew East</option>
        <option value="386" >Keysborough</option>
        <option value="387" >Kilcunda</option>
        <option value="838" >Kilmore</option>
        <option value="388" >Kilsyth</option>
        <option value="389" >Kilsyth South</option>
        <option value="390" >Kinglake</option>
        <option value="391" >Kinglake Central</option>
        <option value="392" >Kinglake West</option>
        <option value="393" >Kings Park</option>
        <option value="394" >Kingsbury</option>
        <option value="395" >Kingsville</option>
        <option value="396" >Knoxfield</option>
        <option value="397" >Kongwak</option>
        <option value="398" >Koo Wee Rup</option>
        <option value="399" >Koo Wee Rup North</option>
        <option value="400" >Kooyong</option>
        <option value="401" >Korobeit</option>
        <option value="403" >Korumburra</option>
        <option value="404" >Korweinguboora</option>
        <option value="405" >Krowera</option>
        <option value="406" >Kurunjang</option>
        <option value="407" >Labertouche</option>
        <option value="408" >Lal Lal</option>
        <option value="409" >Lalor</option>
        <option value="410" >Lance Creek</option>
        <option value="411" >Lang Lang</option>
        <option value="412" >Lang Lang East</option>
        <option value="413" >Langdons Hill</option>
        <option value="414" >Langwarrin</option>
        <option value="415" >Langwarrin South</option>
        <option value="416" >Lara</option>
        <option value="417" >Launching Place</option>
        <option value="418" >Laverton</option>
        <option value="419" >Laverton North</option>
        <option value="420" >Leonards Hill</option>
        <option value="421" >Leongatha South</option>
        <option value="422" >Leopold</option>
        <option value="423" >Lerderderg</option>
        <option value="424" >Lethbridge</option>
        <option value="425" >Lilydale</option>
        <option value="426" >Little Hampton</option>
        <option value="427" >Little River</option>
        <option value="428" >Loch</option>
        <option value="429" >Long Forest</option>
        <option value="430" >Longwarry</option>
        <option value="431" >Longwarry North</option>
        <option value="432" >Lorne</option>
        <option value="433" >Lovely Banks</option>
        <option value="434" >Lower Plenty</option>
        <option value="435" >Lynbrook</option>
        <option value="436" >Lyndhurst</option>
        <option value="437" >Lyonville</option>
        <option value="438" >Lysterfield</option>
        <option value="439" >Lysterfield South</option>
        <option value="440" >Macclesfield</option>
        <option value="441" >Macedon</option>
        <option value="442" >Macleod</option>
        <option value="443" >Maddingley</option>
        <option value="444" >Maidstone</option>
        <option value="445" >Main Ridge</option>
        <option value="446" >Malvern</option>
        <option value="447" >Malvern East</option>
        <option value="448" >Mambourin</option>
        <option value="449" >Manifold Heights</option>
        <option value="450" >Mannerim</option>
        <option value="451" >Marcus Hill</option>
        <option value="452" >Maribyrnong</option>
        <option value="453" >Marshall</option>
        <option value="454" >Maryknoll</option>
        <option value="455" >Marysville</option>
        <option value="456" >Maude</option>
        <option value="457" >Mccrae</option>
        <option value="458" >Mckinnon</option>
        <option value="459" >Mcmahons Creek</option>
        <option value="460" >Meadow Heights</option>
        <option value="461" >Melbourne</option>
        <option value="462" >Melbourne Airport</option>
        <option value="463" >Melton</option>
        <option value="464" >Melton South</option>
        <option value="465" >Melton West</option>
        <option value="466" >Mentone</option>
        <option value="467" >Menzies Creek</option>
        <option value="468" >Meredith</option>
        <option value="469" >Mernda</option>
        <option value="470" >Merricks</option>
        <option value="471" >Merricks Beach</option>
        <option value="472" >Merricks North</option>
        <option value="473" >Merrimu</option>
        <option value="474" >Mickleham</option>
        <option value="475" >Middle Park</option>
        <option value="476" >Mill Park</option>
        <option value="477" >Millbrook</option>
        <option value="478" >Millgrove</option>
        <option value="479" >Mitcham</option>
        <option value="480" >Modella</option>
        <option value="481" >Modewarre</option>
        <option value="482" >Moggs Creek</option>
        <option value="483" >Mollongghip</option>
        <option value="484" >Monbulk</option>
        <option value="485" >Monegeetta</option>
        <option value="486" >Monomeith</option>
        <option value="487" >Mont Albert</option>
        <option value="488" >Mont Albert North</option>
        <option value="490" >Montmorency</option>
        <option value="491" >Montrose</option>
        <option value="492" >Moolap</option>
        <option value="493" >Moonee Ponds</option>
        <option value="494" >Moorabbin</option>
        <option value="495" >Moorabbin Airport</option>
        <option value="496" >Moorabool</option>
        <option value="497" >Moorooduc</option>
        <option value="498" >Mooroolbark</option>
        <option value="499" >Mordialloc</option>
        <option value="501" >Moriac</option>
        <option value="502" >Mornington</option>
        <option value="503" >Morrisons</option>
        <option value="504" >Mount Burnett</option>
        <option value="505" >Mount Cottrell</option>
        <option value="506" >Mount Dandenong</option>
        <option value="507" >Mount Doran</option>
        <option value="508" >Mount Duneed</option>
        <option value="509" >Mount Egerton</option>
        <option value="510" >Mount Eliza</option>
        <option value="511" >Mount Evelyn</option>
        <option value="512" >Mount Macedon</option>
        <option value="513" >Mount Martha</option>
        <option value="514" >Mount Moriac</option>
        <option value="515" >Mount Prospect</option>
        <option value="516" >Mount Toolebewong</option>
        <option value="517" >Mount Wallace</option>
        <option value="518" >Mount Waverley</option>
        <option value="519" >Moyarra</option>
        <option value="520" >Mulgrave</option>
        <option value="521" >Murgheboluc</option>
        <option value="522" >Murrindindi</option>
        <option value="523" >Murrumbeena</option>
        <option value="524" >Musk</option>
        <option value="525" >Musk Vale</option>
        <option value="526" >Myrniong</option>
        <option value="527" >Nangana</option>
        <option value="528" >Nar Nar Goon</option>
        <option value="529" >Nar Nar Goon North</option>
        <option value="530" >Narbethong</option>
        <option value="531" >Narre Warren</option>
        <option value="532" >Narre Warren East</option>
        <option value="533" >Narre Warren North</option>
        <option value="534" >Narre Warren South</option>
        <option value="535" >New Gisborne</option>
        <option value="536" >Newbury</option>
        <option value="537" >Newcomb</option>
        <option value="538" >Newhaven</option>
        <option value="539" >Newlyn</option>
        <option value="540" >Newlyn North</option>
        <option value="541" >Newport</option>
        <option value="542" >Newtown</option>
        <option value="543" >Newtown (Geelong)</option>
        <option value="544" >Niddrie</option>
        <option value="545" >Noble Park</option>
        <option value="546" >Noble Park North</option>
        <option value="547" >Norlane</option>
        <option value="548" >North Blackwood</option>
        <option value="549" >North Geelong</option>
        <option value="550" >North Melbourne</option>
        <option value="551" >North Shore</option>
        <option value="552" >North Warrandyte</option>
        <option value="553" >North Wonthaggi</option>
        <option value="554" >Northcote</option>
        <option value="555" >Notting Hill</option>
        <option value="556" >Nunawading</option>
        <option value="557" >Nutfield</option>
        <option value="558" >Nyora</option>
        <option value="559" >Oak Park</option>
        <option value="560" >Oaklands Junction</option>
        <option value="561" >Oakleigh</option>
        <option value="562" >Oakleigh East</option>
        <option value="563" >Oakleigh South</option>
        <option value="564" >Ocean Grove</option>
        <option value="565" >Officer</option>
        <option value="566" >Officer South</option>
        <option value="567" >Olinda</option>
        <option value="568" >Ormond</option>
        <option value="569" >Outtrim</option>
        <option value="570" >Pakenham</option>
        <option value="571" >Pakenham South</option>
        <option value="572" >Pakenham Upper</option>
        <option value="573" >Panton Hill</option>
        <option value="574" >Paraparap</option>
        <option value="575" >Park Orchards</option>
        <option value="576" >Parkdale</option>
        <option value="577" >Parkville</option>
        <option value="578" >Parwan</option>
        <option value="579" >Pascoe Vale</option>
        <option value="580" >Pascoe Vale South</option>
        <option value="581" >Patterson Lakes</option>
        <option value="582" >Pearcedale</option>
        <option value="583" >Pentland Hills</option>
        <option value="585" >Pheasant Creek</option>
        <option value="586" >Pioneer Bay</option>
        <option value="587" >Plenty</option>
        <option value="588" >Plumpton</option>
        <option value="589" >Point Cook</option>
        <option value="590" >Point Leo</option>
        <option value="591" >Point Lonsdale</option>
        <option value="592" >Point Wilson</option>
        <option value="593" >Poowong</option>
        <option value="594" >Poowong North</option>
        <option value="595" >Port Melbourne</option>
        <option value="596" >Portarlington</option>
        <option value="597" >Portsea</option>
        <option value="598" >Powelltown</option>
        <option value="600" >Prahran</option>
        <option value="601" >Preston</option>
        <option value="602" >Princes Hill</option>
        <option value="603" >Quandong</option>
        <option value="604" >Queenscliff</option>
        <option value="605" >Queensferry</option>
        <option value="606" >Ravenhall</option>
        <option value="608" >Red Hill</option>
        <option value="609" >Red Hill South</option>
        <option value="610" >Research</option>
        <option value="611" >Reservoir</option>
        <option value="612" >Rhyll</option>
        <option value="613" >Richmond</option>
        <option value="614" >Riddells Creek</option>
        <option value="615" >Ringwood</option>
        <option value="616" >Ringwood East</option>
        <option value="617" >Ringwood North</option>
        <option value="618" >Ripplebrook</option>
        <option value="619" >Rippleside</option>
        <option value="620" >Ripponlea</option>
        <option value="622" >Rockbank</option>
        <option value="623" >Rocklyn</option>
        <option value="624" >Romsey</option>
        <option value="625" >Rosanna</option>
        <option value="626" >Rosebud</option>
        <option value="627" >Rosebud West</option>
        <option value="628" >Rowsley</option>
        <option value="629" >Rowville</option>
        <option value="630" >Roxburgh Park</option>
        <option value="632" >Rubicon</option>
        <option value="633" >Russells Bridge</option>
        <option value="634" >Ryanston</option>
        <option value="635" >Rye</option>
        <option value="636" >Rythdale</option>
        <option value="637" >Safety Beach</option>
        <option value="638" >Sailors Falls</option>
        <option value="639" >Sailors Hill</option>
        <option value="641" >Saint Helena</option>
        <option value="642" >San Remo</option>
        <option value="643" >Sandhurst</option>
        <option value="644" >Sandringham</option>
        <option value="645" >Sassafras</option>
        <option value="646" >Scoresby</option>
        <option value="647" >Seabrook</option>
        <option value="648" >Seaford</option>
        <option value="649" >Seaholme</option>
        <option value="650" >Seddon</option>
        <option value="651" >Selby</option>
        <option value="652" >Seville</option>
        <option value="653" >Seville East</option>
        <option value="654" >She Oaks</option>
        <option value="655" >Sherbrooke</option>
        <option value="656" >Shoreham</option>
        <option value="657" >Silvan</option>
        <option value="658" >Silverleaves</option>
        <option value="659" >Skye</option>
        <option value="660" >Smiths Beach</option>
        <option value="661" >Smiths Gully</option>
        <option value="662" >Somers</option>
        <option value="663" >Somerton</option>
        <option value="664" >Somerville</option>
        <option value="665" >Sorrento</option>
        <option value="666" >South Dudley</option>
        <option value="667" >South Geelong</option>
        <option value="668" >South Kingsville</option>
        <option value="669" >South Melbourne</option>
        <option value="670" >South Morang</option>
        <option value="671" >South Wharf</option>
        <option value="672" >South Yarra</option>
        <option value="673" >Southbank</option>
        <option value="674" >Spargo Creek</option>
        <option value="675" >Spotswood</option>
        <option value="677" >Springbank</option>
        <option value="1073" >Springfield</option>
        <option value="678" >Springvale</option>
        <option value="679" >Springvale South</option>
        <option value="680" >St Albans</option>
        <option value="681" >St Albans Park</option>
        <option value="682" >St Andrews</option>
        <option value="683" >St Andrews Beach</option>
        <option value="684" >St Clair</option>
        <option value="685" >St Helena</option>
        <option value="686" >St Kilda</option>
        <option value="687" >St Kilda East</option>
        <option value="688" >St Kilda West</option>
        <option value="689" >St Leonards</option>
        <option value="690" >Staughton Vale</option>
        <option value="691" >Steels Creek</option>
        <option value="692" >Steiglitz</option>
        <option value="693" >Stonehaven</option>
        <option value="694" >Strathewen</option>
        <option value="695" >Strathmore</option>
        <option value="696" >Strathmore Heights</option>
        <option value="697" >Summerlands</option>
        <option value="698" >Sunbury</option>
        <option value="699" >Sunderland Bay</option>
        <option value="700" >Sunset Strip</option>
        <option value="701" >Sunshine</option>
        <option value="702" >Sunshine North</option>
        <option value="703" >Sunshine West</option>
        <option value="704" >Surf Beach</option>
        <option value="705" >Surrey Hills</option>
        <option value="706" >Sutherlands Creek</option>
        <option value="707" >Swan Bay</option>
        <option value="708" >Swan Island</option>
        <option value="709" >Sydenham</option>
        <option value="710" >Taggerty</option>
        <option value="712" >Tarneit</option>
        <option value="714" >Tarrawarra</option>
        <option value="715" >Taylors Hill</option>
        <option value="716" >Taylors Lakes</option>
        <option value="717" >Tecoma</option>
        <option value="718" >Teesdale</option>
        <option value="719" >Templestowe</option>
        <option value="720" >Templestowe Lower</option>
        <option value="721" >Tenby Point</option>
        <option value="722" >The Basin</option>
        <option value="723" >The Gurdies</option>
        <option value="724" >The Patch</option>
        <option value="725" >Thomastown</option>
        <option value="726" >Thomson</option>
        <option value="727" >Thornbury</option>
        <option value="728" >Three Bridges</option>
        <option value="729" >Tonimbuk</option>
        <option value="730" >Toolangi</option>
        <option value="731" >Toolern Vale</option>
        <option value="732" >Tooradin</option>
        <option value="733" >Toorak</option>
        <option value="734" >Tootgarook</option>
        <option value="735" >Torquay</option>
        <option value="736" >Tottenham</option>
        <option value="737" >Travancore</option>
        <option value="738" >Tremont</option>
        <option value="739" >Trentham</option>
        <option value="740" >Trentham East</option>
        <option value="741" >Truganina</option>
        <option value="742" >Tuerong</option>
        <option value="743" >Tullamarine</option>
        <option value="744" >Tyabb</option>
        <option value="745" >Tynong</option>
        <option value="746" >Tynong North</option>
        <option value="747" >Upper Ferntree Gully</option>
        <option value="748" >Upper Plenty</option>
        <option value="749" >Upwey</option>
        <option value="750" >Ventnor</option>
        <option value="751" >Vermont</option>
        <option value="752" >Vermont South</option>
        <option value="753" >Vervale</option>
        <option value="754" >Viewbank</option>
        <option value="755" >Wallace</option>
        <option value="756" >Wallan</option>
        <option value="758" >Wallington</option>
        <option value="759" >Wandana Heights</option>
        <option value="761" >Wandin East</option>
        <option value="762" >Wandin North</option>
        <option value="764" >Wandong</option>
        <option value="765" >Wantirna</option>
        <option value="766" >Wantirna South</option>
        <option value="767" >Warburton</option>
        <option value="1048" >Warburton East</option>
        <option value="768" >Warneet</option>
        <option value="1071" >Warragul</option>
        <option value="769" >Warrandyte</option>
        <option value="770" >Warrandyte South</option>
        <option value="771" >Warranwood</option>
        <option value="772" >Waterways</option>
        <option value="773" >Watsonia</option>
        <option value="774" >Watsonia North</option>
        <option value="775" >Watsons Creek</option>
        <option value="776" >Wattle Bank</option>
        <option value="777" >Wattle Glen</option>
        <option value="778" >Waurn Ponds</option>
        <option value="779" >Wensleydale</option>
        <option value="780" >Werribee</option>
        <option value="781" >Werribee South</option>
        <option value="782" >Wesburn</option>
        <option value="783" >West Creek</option>
        <option value="784" >West Footscray</option>
        <option value="785" >West Melbourne</option>
        <option value="787" >Westmeadows</option>
        <option value="1074" >Wheatsheaf</option>
        <option value="788" >Wheelers Hill</option>
        <option value="789" >Whitelaw</option>
        <option value="790" >Whittington</option>
        <option value="791" >Whittlesea</option>
        <option value="792" >Wildwood</option>
        <option value="793" >Williams Landing</option>
        <option value="794" >Williamstown</option>
        <option value="795" >Williamstown North</option>
        <option value="796" >Wimbledon Heights</option>
        <option value="797" >Winchelsea</option>
        <option value="798" >Winchelsea South</option>
        <option value="799" >Windsor</option>
        <option value="800" >Wollert</option>
        <option value="801" >Wonga Park</option>
        <option value="802" >Wonthaggi</option>
        <option value="803" >Woodend</option>
        <option value="804" >Woodleigh</option>
        <option value="806" >Woodstock</option>
        <option value="807" >Woolamai</option>
        <option value="808" >Woori Yallock</option>
        <option value="810" >Wurdiboluc</option>
        <option value="811" >Wyndham Vale</option>
        <option value="812" >Yallambie</option>
        <option value="814" >Yan Yean</option>
        <option value="815" >Yannathan</option>
        <option value="816" >Yarra Glen</option>
        <option value="817" >Yarra Junction</option>
        <option value="818" >Yarrambat</option>
        <option value="819" >Yarraville</option>
        <option value="820" >Yellingbo</option>
        <option value="821" >Yering</option>
        <option value="822" >Yuroke</option>
      </select>
      <input type="hidden" name="pSuburb" id="text_content" value="" />   
          </div>
        </div>
        <div class="row">

          <div class="form-group col-sm-6" >
             <h3><input type="text" name="fNo" class="form-control" placeholder="Flight No(if pickup from airport)"></h3>
          </div>
          <div class="form-group col-sm-offset-1 col-sm-5 " >
            
          </div>
        </div>
        <div class="row">

          <div class="form-group col-sm-6" >
             
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12" ><p >Drop Off Details</p></div>
          <div class="form-group col-sm-6" style="padding-left:0px; padding-right:0px" >
            <div class="form-group col-sm-3">
              <input type="text" name="dUnit" class="form-control" placeholder="Unit/Flat No (OPTIONAL)" value = "<?php if(isset($_SESSION['dUnit'])) echo $_SESSION['dUnit']; ?>"></h3>
            </div>
             <div class="form-group col-sm-offset-1 col-sm-7">
               <h3><input type="text" name="dAddress" class="form-control" placeholder="Street Name (OPTIONAL)" value = "<?php if(isset($_SESSION['dAddress'])) echo $_SESSION['pAddress']; ?>"></h3>
             </div>
          </div>
           <div class="form-group col-sm-offset-1 col-sm-5" >
            
            <h3><select  class="form-control" onchange="document.getElementById('text_content1').value=this.options[this.selectedIndex].text"  ></h3>
        <option value="">Please Select Suburb</option>
        <option value="Abbotsford" >Abbotsford</option>
        <option value="Aberfeldie" >Aberfeldie</option>
        <option value="Adams Estate" >Adams Estate</option>
        <option value="Aireys Inlet" >Aireys Inlet</option>
        <option value="Airport West" >Airport West</option>
        <option value="Albanvale" >Albanvale</option>
        <option value="7" >Albert Park</option>
        <option value="8" >Albion</option>
        <option value="9" >Almurta</option>
        <option value="10" >Alphington</option>
        <option value="11" >Altona</option>
        <option value="12" >Altona Meadows</option>
        <option value="13" >Altona North</option>
        <option value="14" >Anakie</option>
        <option value="15" >Anderson</option>
        <option value="16" >Anglesea</option>
        <option value="17" >Archies Creek</option>
        <option value="18" >Ardeer</option>
        <option value="19" >Armadale</option>
        <option value="20" >Arthurs Creek</option>
        <option value="21" >Arthurs Seat</option>
        <option value="1056" >As Directed</option>
        <option value="22" >Ascot Vale</option>
        <option value="23" >Ashbourne</option>
        <option value="24" >Ashburton</option>
        <option value="25" >Ashwood</option>
        <option value="26" >Aspendale</option>
        <option value="27" >Aspendale Gardens</option>
        <option value="28" >Athlone</option>
        <option value="29" >Attwood</option>
        <option value="30" >Avalon</option>
        <option value="31" >Avondale Heights</option>
        <option value="32" >Avonsleigh</option>
        <option value="33" >Bacchus Marsh</option>
        <option value="34" >Badger Creek</option>
        <option value="35" >Balaclava</option>
        <option value="36" >Ballan</option>
        <option value="37" >Balliang</option>
        <option value="38" >Balliang East</option>
        <option value="39" >Balnarring</option>
        <option value="40" >Balnarring Beach</option>
        <option value="41" >Balwyn</option>
        <option value="42" >Balwyn North</option>
        <option value="43" >Bambra</option>
        <option value="44" >Bamganie</option>
        <option value="45" >Bangholme</option>
        <option value="46" >Bannockburn</option>
        <option value="47" >Barkstead</option>
        <option value="48" >Barrabool</option>
        <option value="49" >Barrys Reef</option>
        <option value="50" >Barwon Heads</option>
        <option value="51" >Bass</option>
        <option value="52" >Batesford</option>
        <option value="53" >Baxter</option>
        <option value="54" >Bayles</option>
        <option value="55" >Bayswater</option>
        <option value="56" >Bayswater North</option>
        <option value="57" >Beaconsfield</option>
        <option value="58" >Beaconsfield Upper</option>
        <option value="59" >Beaumaris</option>
        <option value="60" >Beenak</option>
        <option value="61" >Belgrave</option>
        <option value="62" >Belgrave Heights</option>
        <option value="63" >Belgrave South</option>
        <option value="64" >Bell Park</option>
        <option value="65" >Bell Post Hill</option>
        <option value="66" >Bellarine</option>
        <option value="67" >Bellbrae</option>
        <option value="68" >Bellfield</option>
        <option value="69" >Bellfield (Greater Melbourne)</option>
        <option value="70" >Bells Beach</option>
        <option value="71" >Belmont</option>
        <option value="72" >Bena</option>
        <option value="73" >Bend Of Islands</option>
        <option value="74" >Bentleigh</option>
        <option value="75" >Bentleigh East</option>
        <option value="76" >Beremboke</option>
        <option value="77" >Berwick</option>
        <option value="78" >Beveridge</option>
        <option value="79" >Big Hill</option>
        <option value="80" >Big Hill (Lorne)</option>
        <option value="81" >Big Pats Creek</option>
        <option value="82" >Bittern</option>
        <option value="83" >Black Rock</option>
        <option value="84" >Blackburn</option>
        <option value="85" >Blackburn North</option>
        <option value="86" >Blackburn South</option>
        <option value="87" >Blackwood</option>
        <option value="88" >Blairgowrie</option>
        <option value="89" >Blakeville</option>
        <option value="90" >Blampied</option>
        <option value="91" >Blind Bight</option>
        <option value="92" >Bolinda</option>
        <option value="93" >Bolwarrah</option>
        <option value="94" >Bonbeach</option>
        <option value="95" >Boneo</option>
        <option value="96" >Boonah</option>
        <option value="97" >Boronia</option>
        <option value="98" >Botanic Ridge</option>
        <option value="99" >Box Hill</option>
        <option value="100" >Box Hill North</option>
        <option value="101" >Box Hill South</option>
        <option value="102" >Braeside</option>
        <option value="103" >Braybrook</option>
        <option value="104" >Breakwater</option>
        <option value="105" >Breamlea</option>
        <option value="106" >Briar Hill</option>
        <option value="107" >Brighton</option>
        <option value="108" >Brighton East</option>
        <option value="109" >Broadmeadows</option>
        <option value="110" >Brookfield</option>
        <option value="111" >Brooklyn</option>
        <option value="113" >Brunswick</option>
        <option value="114" >Brunswick East</option>
        <option value="115" >Brunswick West</option>
        <option value="116" >Buckley</option>
        <option value="117" >Bulla</option>
        <option value="118" >Bullarook</option>
        <option value="119" >Bullarto</option>
        <option value="120" >Bullarto South</option>
        <option value="121" >Bulleen</option>
        <option value="122" >Bullengarook</option>
        <option value="123" >Bunding</option>
        <option value="124" >Bundoora</option>
        <option value="125" >Bungal</option>
        <option value="126" >Bungaree</option>
        <option value="127" >Bunyip</option>
        <option value="128" >Bunyip North</option>
        <option value="129" >Burnley</option>
        <option value="130" >Burnside</option>
        <option value="131" >Burnside Heights</option>
        <option value="132" >Burwood</option>
        <option value="133" >Burwood East</option>
        <option value="134" >Buxton</option>
        <option value="135" >Bylands</option>
        <option value="136" >Cairnlea</option>
        <option value="137" >Calder Park</option>
        <option value="138" >Caldermeade</option>
        <option value="139" >Camberwell</option>
        <option value="140" >Campbellfield</option>
        <option value="141" >Cannons Creek</option>
        <option value="142" >Canterbury</option>
        <option value="143" >Cape Schanck</option>
        <option value="144" >Cape Woolamai</option>
        <option value="145" >Cardinia</option>
        <option value="146" >Carlton</option>
        <option value="147" >Carlton North</option>
        <option value="148" >Carnegie</option>
        <option value="149" >Caroline Springs</option>
        <option value="150" >Carrum</option>
        <option value="151" >Carrum Downs</option>
        <option value="152" >Castella</option>
        <option value="153" >Catani</option>
        <option value="154" >Caulfield</option>
        <option value="155" >Caulfield East</option>
        <option value="156" >Caulfield North</option>
        <option value="157" >Caulfield South</option>
        <option value="158" >Ceres</option>
        <option value="159" >Chadstone</option>
        <option value="1076" >Charlton</option>
        <option value="161" >Chelsea</option>
        <option value="162" >Chelsea Heights</option>
        <option value="163" >Cheltenham</option>
        <option value="164" >Cherokee</option>
        <option value="165" >Chintin</option>
        <option value="166" >Chirnside Park</option>
        <option value="167" >Christmas Hills</option>
        <option value="168" >Chum Creek</option>
        <option value="823" >City</option>
        <option value="1075" >City Special</option>
        <option value="170" >Claretown</option>
        <option value="171" >Clarinda</option>
        <option value="172" >Clarkefield</option>
        <option value="173" >Clayton</option>
        <option value="174" >Clayton South</option>
        <option value="175" >Clematis</option>
        <option value="176" >Clifton Hill</option>
        <option value="177" >Clifton Springs</option>
        <option value="178" >Clonbinane</option>
        <option value="179" >Clyde</option>
        <option value="180" >Clyde North</option>
        <option value="181" >Coburg</option>
        <option value="182" >Coburg North</option>
        <option value="183" >Cockatoo</option>
        <option value="184" >Cocoroc</option>
        <option value="185" >Coimadai</option>
        <option value="186" >Colbrook</option>
        <option value="187" >Coldstream</option>
        <option value="188" >Collingwood</option>
        <option value="189" >Connewarre</option>
        <option value="190" >Coolaroo</option>
        <option value="191" >Cora Lynn</option>
        <option value="192" >Corinella</option>
        <option value="193" >Corio</option>
        <option value="194" >Coronet Bay</option>
        <option value="195" >Cottles Bridge</option>
        <option value="196" >Cowes</option>
        <option value="197" >Craigieburn</option>
        <option value="198" >Cranbourne</option>
        <option value="199" >Cranbourne East</option>
        <option value="200" >Cranbourne North</option>
        <option value="201" >Cranbourne South</option>
        <option value="202" >Cranbourne West</option>
        <option value="203" >Cremorne</option>
        <option value="204" >Crib Point</option>
        <option value="205" >Croydon</option>
        <option value="206" >Croydon Hills</option>
        <option value="207" >Croydon North</option>
        <option value="208" >Croydon South</option>
        <option value="209" >Curlewis</option>
        <option value="210" >Dales Creek</option>
        <option value="211" >Dallas</option>
        <option value="212" >Dalmore</option>
        <option value="213" >Dalyston</option>
        <option value="214" >Dandenong</option>
        <option value="215" >Dandenong North</option>
        <option value="216" >Dandenong South</option>
        <option value="217" >Darley</option>
        <option value="218" >Darraweit Guim</option>
        <option value="219" >Daylesford</option>
        <option value="220" >Dean</option>
        <option value="1072" >Deepdene</option>
        <option value="221" >Deer Park</option>
        <option value="222" >Delahey</option>
        <option value="223" >Derrimut</option>
        <option value="224" >Devon Meadows</option>
        <option value="225" >Dewhurst</option>
        <option value="226" >Diamond Creek</option>
        <option value="227" >Diggers Rest</option>
        <option value="228" >Dingley Village</option>
        <option value="229" >Dixons Creek</option>
        <option value="230" >Docklands</option>
        <option value="231" >Don Valley</option>
        <option value="232" >Doncaster</option>
        <option value="233" >Doncaster East</option>
        <option value="234" >Donnybrook</option>
        <option value="235" >Donvale</option>
        <option value="236" >Doreen</option>
        <option value="237" >Doveton</option>
        <option value="238" >Dromana</option>
        <option value="239" >Drouin South</option>
        <option value="240" >Drumcondra</option>
        <option value="241" >Drysdale</option>
        <option value="243" >Durdidwarrah</option>
        <option value="244" >Eaglemont</option>
        <option value="245" >East Geelong</option>
        <option value="246" >East Melbourne</option>
        <option value="247" >East Warburton</option>
        <option value="248" >Eastern View</option>
        <option value="249" >Eden Park</option>
        <option value="250" >Edithvale</option>
        <option value="251" >Eganstown</option>
        <option value="252" >Elaine</option>
        <option value="253" >Elsternwick</option>
        <option value="254" >Eltham</option>
        <option value="255" >Eltham North</option>
        <option value="256" >Elwood</option>
        <option value="257" >Emerald</option>
        <option value="258" >Endeavour Hills</option>
        <option value="259" >Epping</option>
        <option value="829" >Epping North</option>
        <option value="260" >Essendon</option>
        <option value="261" >Essendon Fields</option>
        <option value="262" >Essendon North</option>
        <option value="263" >Essendon West</option>
        <option value="264" >Eumemmerring</option>
        <option value="265" >Exford</option>
        <option value="266" >Eynesbury</option>
        <option value="267" >Fairfield</option>
        <option value="268" >Fairhaven</option>
        <option value="269" >Fawkner</option>
        <option value="270" >Fern Hill</option>
        <option value="271" >Fernshaw</option>
        <option value="272" >Ferntree Gully</option>
        <option value="273" >Ferny Creek</option>
        <option value="274" >Fingal</option>
        <option value="275" >Fiskville</option>
        <option value="276" >Fitzroy</option>
        <option value="277" >Fitzroy North</option>
        <option value="278" >Flemington</option>
        <option value="279" >Flinders</option>
        <option value="280" >Flowerdale</option>
        <option value="281" >Footscray</option>
        <option value="282" >Forest Hill</option>
        <option value="283" >Frankston</option>
        <option value="284" >Frankston North</option>
        <option value="285" >Frankston South</option>
        <option value="286" >French Island</option>
        <option value="287" >Freshwater Creek</option>
        <option value="288" >Fyansford</option>
        <option value="289" >Gardenvale</option>
        <option value="290" >Garfield</option>
        <option value="291" >Garfield North</option>
        <option value="292" >Geelong</option>
        <option value="293" >Geelong West</option>
        <option value="294" >Gembrook</option>
        <option value="295" >Gentle Annie</option>
        <option value="296" >Gherang</option>
        <option value="297" >Gheringhap</option>
        <option value="298" >Gilderoy</option>
        <option value="299" >Gisborne</option>
        <option value="300" >Gisborne South</option>
        <option value="301" >Gladstone Park</option>
        <option value="302" >Gladysdale</option>
        <option value="303" >Glen Alvie</option>
        <option value="304" >Glen Forbes</option>
        <option value="305" >Glen Huntly</option>
        <option value="306" >Glen Iris</option>
        <option value="307" >Glen Waverley</option>
        <option value="308" >Glenburn</option>
        <option value="309" >Glenmore</option>
        <option value="310" >Glenroy</option>
        <option value="311" >Gnarwarre</option>
        <option value="312" >Gordon</option>
        <option value="313" >Gowanbrae</option>
        <option value="314" >Grantville</option>
        <option value="315" >Greendale</option>
        <option value="316" >Greensborough</option>
        <option value="317" >Greenvale</option>
        <option value="318" >Grovedale</option>
        <option value="319" >Gruyere</option>
        <option value="320" >Guys Hill</option>
        <option value="321" >Hadfield</option>
        <option value="322" >Hallam</option>
        <option value="323" >Hamlyn Heights</option>
        <option value="324" >Hampton</option>
        <option value="325" >Hampton East</option>
        <option value="326" >Hampton Park</option>
        <option value="328" >Harkaway</option>
        <option value="329" >Hastings</option>
        <option value="330" >Hawthorn</option>
        <option value="331" >Hawthorn East</option>
        <option value="332" >Hazeldene</option>
        <option value="333" >Healesville</option>
        <option value="334" >Heath Hill</option>
        <option value="335" >Heathcote Junction</option>
        <option value="336" >Heatherton</option>
        <option value="337" >Heathmont</option>
        <option value="338" >Heidelberg</option>
        <option value="339" >Heidelberg Heights</option>
        <option value="340" >Heidelberg West</option>
        <option value="341" >Herne Hill</option>
        <option value="342" >Hesket</option>
        <option value="344" >Highett</option>
        <option value="345" >Highton</option>
        <option value="346" >Hillside</option>
        <option value="347" >Hillside (Melton)</option>
        <option value="348" >Hmas Cerberus</option>
        <option value="349" >Hoddles Creek</option>
        <option value="350" >Hopetoun Park</option>
        <option value="351" >Hoppers Crossing</option>
        <option value="352" >Hughesdale</option>
        <option value="353" >Humevale</option>
        <option value="354" >Huntingdale</option>
        <option value="355" >Hurstbridge</option>
        <option value="356" >Indented Head</option>
        <option value="357" >Ingliston</option>
        <option value="358" >Inverleigh</option>
        <option value="359" >Inverloch</option>
        <option value="360" >Iona</option>
        <option value="361" >Ivanhoe</option>
        <option value="362" >Ivanhoe East</option>
        <option value="363" >Jacana</option>
        <option value="364" >Jam Jerrup</option>
        <option value="365" >Jan Juc</option>
        <option value="366" >Jeetho</option>
        <option value="368" >Jumbunna</option>
        <option value="369" >Junction Village</option>
        <option value="370" >Kalkallo</option>
        <option value="371" >Kallista</option>
        <option value="372" >Kalorama</option>
        <option value="1051" >Kananook</option>
        <option value="373" >Kangaroo Ground</option>
        <option value="374" >Kealba</option>
        <option value="375" >Keilor</option>
        <option value="376" >Keilor Downs</option>
        <option value="377" >Keilor East</option>
        <option value="378" >Keilor Lodge</option>
        <option value="379" >Keilor North</option>
        <option value="380" >Keilor Park</option>
        <option value="381" >Kensington</option>
        <option value="382" >Kernot</option>
        <option value="383" >Kerrie</option>
        <option value="384" >Kew</option>
        <option value="385" >Kew East</option>
        <option value="386" >Keysborough</option>
        <option value="387" >Kilcunda</option>
        <option value="838" >Kilmore</option>
        <option value="388" >Kilsyth</option>
        <option value="389" >Kilsyth South</option>
        <option value="390" >Kinglake</option>
        <option value="391" >Kinglake Central</option>
        <option value="392" >Kinglake West</option>
        <option value="393" >Kings Park</option>
        <option value="394" >Kingsbury</option>
        <option value="395" >Kingsville</option>
        <option value="396" >Knoxfield</option>
        <option value="397" >Kongwak</option>
        <option value="398" >Koo Wee Rup</option>
        <option value="399" >Koo Wee Rup North</option>
        <option value="400" >Kooyong</option>
        <option value="401" >Korobeit</option>
        <option value="403" >Korumburra</option>
        <option value="404" >Korweinguboora</option>
        <option value="405" >Krowera</option>
        <option value="406" >Kurunjang</option>
        <option value="407" >Labertouche</option>
        <option value="408" >Lal Lal</option>
        <option value="409" >Lalor</option>
        <option value="410" >Lance Creek</option>
        <option value="411" >Lang Lang</option>
        <option value="412" >Lang Lang East</option>
        <option value="413" >Langdons Hill</option>
        <option value="414" >Langwarrin</option>
        <option value="415" >Langwarrin South</option>
        <option value="416" >Lara</option>
        <option value="417" >Launching Place</option>
        <option value="418" >Laverton</option>
        <option value="419" >Laverton North</option>
        <option value="420" >Leonards Hill</option>
        <option value="421" >Leongatha South</option>
        <option value="422" >Leopold</option>
        <option value="423" >Lerderderg</option>
        <option value="424" >Lethbridge</option>
        <option value="425" >Lilydale</option>
        <option value="426" >Little Hampton</option>
        <option value="427" >Little River</option>
        <option value="428" >Loch</option>
        <option value="429" >Long Forest</option>
        <option value="430" >Longwarry</option>
        <option value="431" >Longwarry North</option>
        <option value="432" >Lorne</option>
        <option value="433" >Lovely Banks</option>
        <option value="434" >Lower Plenty</option>
        <option value="435" >Lynbrook</option>
        <option value="436" >Lyndhurst</option>
        <option value="437" >Lyonville</option>
        <option value="438" >Lysterfield</option>
        <option value="439" >Lysterfield South</option>
        <option value="440" >Macclesfield</option>
        <option value="441" >Macedon</option>
        <option value="442" >Macleod</option>
        <option value="443" >Maddingley</option>
        <option value="444" >Maidstone</option>
        <option value="445" >Main Ridge</option>
        <option value="446" >Malvern</option>
        <option value="447" >Malvern East</option>
        <option value="448" >Mambourin</option>
        <option value="449" >Manifold Heights</option>
        <option value="450" >Mannerim</option>
        <option value="451" >Marcus Hill</option>
        <option value="452" >Maribyrnong</option>
        <option value="453" >Marshall</option>
        <option value="454" >Maryknoll</option>
        <option value="455" >Marysville</option>
        <option value="456" >Maude</option>
        <option value="457" >Mccrae</option>
        <option value="458" >Mckinnon</option>
        <option value="459" >Mcmahons Creek</option>
        <option value="460" >Meadow Heights</option>
        <option value="461" >Melbourne</option>
        <option value="462" >Melbourne Airport</option>
        <option value="463" >Melton</option>
        <option value="464" >Melton South</option>
        <option value="465" >Melton West</option>
        <option value="466" >Mentone</option>
        <option value="467" >Menzies Creek</option>
        <option value="468" >Meredith</option>
        <option value="469" >Mernda</option>
        <option value="470" >Merricks</option>
        <option value="471" >Merricks Beach</option>
        <option value="472" >Merricks North</option>
        <option value="473" >Merrimu</option>
        <option value="474" >Mickleham</option>
        <option value="475" >Middle Park</option>
        <option value="476" >Mill Park</option>
        <option value="477" >Millbrook</option>
        <option value="478" >Millgrove</option>
        <option value="479" >Mitcham</option>
        <option value="480" >Modella</option>
        <option value="481" >Modewarre</option>
        <option value="482" >Moggs Creek</option>
        <option value="483" >Mollongghip</option>
        <option value="484" >Monbulk</option>
        <option value="485" >Monegeetta</option>
        <option value="486" >Monomeith</option>
        <option value="487" >Mont Albert</option>
        <option value="488" >Mont Albert North</option>
        <option value="490" >Montmorency</option>
        <option value="491" >Montrose</option>
        <option value="492" >Moolap</option>
        <option value="493" >Moonee Ponds</option>
        <option value="494" >Moorabbin</option>
        <option value="495" >Moorabbin Airport</option>
        <option value="496" >Moorabool</option>
        <option value="497" >Moorooduc</option>
        <option value="498" >Mooroolbark</option>
        <option value="499" >Mordialloc</option>
        <option value="501" >Moriac</option>
        <option value="502" >Mornington</option>
        <option value="503" >Morrisons</option>
        <option value="504" >Mount Burnett</option>
        <option value="505" >Mount Cottrell</option>
        <option value="506" >Mount Dandenong</option>
        <option value="507" >Mount Doran</option>
        <option value="508" >Mount Duneed</option>
        <option value="509" >Mount Egerton</option>
        <option value="510" >Mount Eliza</option>
        <option value="511" >Mount Evelyn</option>
        <option value="512" >Mount Macedon</option>
        <option value="513" >Mount Martha</option>
        <option value="514" >Mount Moriac</option>
        <option value="515" >Mount Prospect</option>
        <option value="516" >Mount Toolebewong</option>
        <option value="517" >Mount Wallace</option>
        <option value="518" >Mount Waverley</option>
        <option value="519" >Moyarra</option>
        <option value="520" >Mulgrave</option>
        <option value="521" >Murgheboluc</option>
        <option value="522" >Murrindindi</option>
        <option value="523" >Murrumbeena</option>
        <option value="524" >Musk</option>
        <option value="525" >Musk Vale</option>
        <option value="526" >Myrniong</option>
        <option value="527" >Nangana</option>
        <option value="528" >Nar Nar Goon</option>
        <option value="529" >Nar Nar Goon North</option>
        <option value="530" >Narbethong</option>
        <option value="531" >Narre Warren</option>
        <option value="532" >Narre Warren East</option>
        <option value="533" >Narre Warren North</option>
        <option value="534" >Narre Warren South</option>
        <option value="535" >New Gisborne</option>
        <option value="536" >Newbury</option>
        <option value="537" >Newcomb</option>
        <option value="538" >Newhaven</option>
        <option value="539" >Newlyn</option>
        <option value="540" >Newlyn North</option>
        <option value="541" >Newport</option>
        <option value="542" >Newtown</option>
        <option value="543" >Newtown (Geelong)</option>
        <option value="544" >Niddrie</option>
        <option value="545" >Noble Park</option>
        <option value="546" >Noble Park North</option>
        <option value="547" >Norlane</option>
        <option value="548" >North Blackwood</option>
        <option value="549" >North Geelong</option>
        <option value="550" >North Melbourne</option>
        <option value="551" >North Shore</option>
        <option value="552" >North Warrandyte</option>
        <option value="553" >North Wonthaggi</option>
        <option value="554" >Northcote</option>
        <option value="555" >Notting Hill</option>
        <option value="556" >Nunawading</option>
        <option value="557" >Nutfield</option>
        <option value="558" >Nyora</option>
        <option value="559" >Oak Park</option>
        <option value="560" >Oaklands Junction</option>
        <option value="561" >Oakleigh</option>
        <option value="562" >Oakleigh East</option>
        <option value="563" >Oakleigh South</option>
        <option value="564" >Ocean Grove</option>
        <option value="565" >Officer</option>
        <option value="566" >Officer South</option>
        <option value="567" >Olinda</option>
        <option value="568" >Ormond</option>
        <option value="569" >Outtrim</option>
        <option value="570" >Pakenham</option>
        <option value="571" >Pakenham South</option>
        <option value="572" >Pakenham Upper</option>
        <option value="573" >Panton Hill</option>
        <option value="574" >Paraparap</option>
        <option value="575" >Park Orchards</option>
        <option value="576" >Parkdale</option>
        <option value="577" >Parkville</option>
        <option value="578" >Parwan</option>
        <option value="579" >Pascoe Vale</option>
        <option value="580" >Pascoe Vale South</option>
        <option value="581" >Patterson Lakes</option>
        <option value="582" >Pearcedale</option>
        <option value="583" >Pentland Hills</option>
        <option value="585" >Pheasant Creek</option>
        <option value="586" >Pioneer Bay</option>
        <option value="587" >Plenty</option>
        <option value="588" >Plumpton</option>
        <option value="589" >Point Cook</option>
        <option value="590" >Point Leo</option>
        <option value="591" >Point Lonsdale</option>
        <option value="592" >Point Wilson</option>
        <option value="593" >Poowong</option>
        <option value="594" >Poowong North</option>
        <option value="595" >Port Melbourne</option>
        <option value="596" >Portarlington</option>
        <option value="597" >Portsea</option>
        <option value="598" >Powelltown</option>
        <option value="600" >Prahran</option>
        <option value="601" >Preston</option>
        <option value="602" >Princes Hill</option>
        <option value="603" >Quandong</option>
        <option value="604" >Queenscliff</option>
        <option value="605" >Queensferry</option>
        <option value="606" >Ravenhall</option>
        <option value="608" >Red Hill</option>
        <option value="609" >Red Hill South</option>
        <option value="610" >Research</option>
        <option value="611" >Reservoir</option>
        <option value="612" >Rhyll</option>
        <option value="613" >Richmond</option>
        <option value="614" >Riddells Creek</option>
        <option value="615" >Ringwood</option>
        <option value="616" >Ringwood East</option>
        <option value="617" >Ringwood North</option>
        <option value="618" >Ripplebrook</option>
        <option value="619" >Rippleside</option>
        <option value="620" >Ripponlea</option>
        <option value="622" >Rockbank</option>
        <option value="623" >Rocklyn</option>
        <option value="624" >Romsey</option>
        <option value="625" >Rosanna</option>
        <option value="626" >Rosebud</option>
        <option value="627" >Rosebud West</option>
        <option value="628" >Rowsley</option>
        <option value="629" >Rowville</option>
        <option value="630" >Roxburgh Park</option>
        <option value="632" >Rubicon</option>
        <option value="633" >Russells Bridge</option>
        <option value="634" >Ryanston</option>
        <option value="635" >Rye</option>
        <option value="636" >Rythdale</option>
        <option value="637" >Safety Beach</option>
        <option value="638" >Sailors Falls</option>
        <option value="639" >Sailors Hill</option>
        <option value="641" >Saint Helena</option>
        <option value="642" >San Remo</option>
        <option value="643" >Sandhurst</option>
        <option value="644" >Sandringham</option>
        <option value="645" >Sassafras</option>
        <option value="646" >Scoresby</option>
        <option value="647" >Seabrook</option>
        <option value="648" >Seaford</option>
        <option value="649" >Seaholme</option>
        <option value="650" >Seddon</option>
        <option value="651" >Selby</option>
        <option value="652" >Seville</option>
        <option value="653" >Seville East</option>
        <option value="654" >She Oaks</option>
        <option value="655" >Sherbrooke</option>
        <option value="656" >Shoreham</option>
        <option value="657" >Silvan</option>
        <option value="658" >Silverleaves</option>
        <option value="659" >Skye</option>
        <option value="660" >Smiths Beach</option>
        <option value="661" >Smiths Gully</option>
        <option value="662" >Somers</option>
        <option value="663" >Somerton</option>
        <option value="664" >Somerville</option>
        <option value="665" >Sorrento</option>
        <option value="666" >South Dudley</option>
        <option value="667" >South Geelong</option>
        <option value="668" >South Kingsville</option>
        <option value="669" >South Melbourne</option>
        <option value="670" >South Morang</option>
        <option value="671" >South Wharf</option>
        <option value="672" >South Yarra</option>
        <option value="673" >Southbank</option>
        <option value="674" >Spargo Creek</option>
        <option value="675" >Spotswood</option>
        <option value="677" >Springbank</option>
        <option value="1073" >Springfield</option>
        <option value="678" >Springvale</option>
        <option value="679" >Springvale South</option>
        <option value="680" >St Albans</option>
        <option value="681" >St Albans Park</option>
        <option value="682" >St Andrews</option>
        <option value="683" >St Andrews Beach</option>
        <option value="684" >St Clair</option>
        <option value="685" >St Helena</option>
        <option value="686" >St Kilda</option>
        <option value="687" >St Kilda East</option>
        <option value="688" >St Kilda West</option>
        <option value="689" >St Leonards</option>
        <option value="690" >Staughton Vale</option>
        <option value="691" >Steels Creek</option>
        <option value="692" >Steiglitz</option>
        <option value="693" >Stonehaven</option>
        <option value="694" >Strathewen</option>
        <option value="695" >Strathmore</option>
        <option value="696" >Strathmore Heights</option>
        <option value="697" >Summerlands</option>
        <option value="698" >Sunbury</option>
        <option value="699" >Sunderland Bay</option>
        <option value="700" >Sunset Strip</option>
        <option value="701" >Sunshine</option>
        <option value="702" >Sunshine North</option>
        <option value="703" >Sunshine West</option>
        <option value="704" >Surf Beach</option>
        <option value="705" >Surrey Hills</option>
        <option value="706" >Sutherlands Creek</option>
        <option value="707" >Swan Bay</option>
        <option value="708" >Swan Island</option>
        <option value="709" >Sydenham</option>
        <option value="710" >Taggerty</option>
        <option value="712" >Tarneit</option>
        <option value="714" >Tarrawarra</option>
        <option value="715" >Taylors Hill</option>
        <option value="716" >Taylors Lakes</option>
        <option value="717" >Tecoma</option>
        <option value="718" >Teesdale</option>
        <option value="719" >Templestowe</option>
        <option value="720" >Templestowe Lower</option>
        <option value="721" >Tenby Point</option>
        <option value="722" >The Basin</option>
        <option value="723" >The Gurdies</option>
        <option value="724" >The Patch</option>
        <option value="725" >Thomastown</option>
        <option value="726" >Thomson</option>
        <option value="727" >Thornbury</option>
        <option value="728" >Three Bridges</option>
        <option value="729" >Tonimbuk</option>
        <option value="730" >Toolangi</option>
        <option value="731" >Toolern Vale</option>
        <option value="732" >Tooradin</option>
        <option value="733" >Toorak</option>
        <option value="734" >Tootgarook</option>
        <option value="735" >Torquay</option>
        <option value="736" >Tottenham</option>
        <option value="737" >Travancore</option>
        <option value="738" >Tremont</option>
        <option value="739" >Trentham</option>
        <option value="740" >Trentham East</option>
        <option value="741" >Truganina</option>
        <option value="742" >Tuerong</option>
        <option value="743" >Tullamarine</option>
        <option value="744" >Tyabb</option>
        <option value="745" >Tynong</option>
        <option value="746" >Tynong North</option>
        <option value="747" >Upper Ferntree Gully</option>
        <option value="748" >Upper Plenty</option>
        <option value="749" >Upwey</option>
        <option value="750" >Ventnor</option>
        <option value="751" >Vermont</option>
        <option value="752" >Vermont South</option>
        <option value="753" >Vervale</option>
        <option value="754" >Viewbank</option>
        <option value="755" >Wallace</option>
        <option value="756" >Wallan</option>
        <option value="758" >Wallington</option>
        <option value="759" >Wandana Heights</option>
        <option value="761" >Wandin East</option>
        <option value="762" >Wandin North</option>
        <option value="764" >Wandong</option>
        <option value="765" >Wantirna</option>
        <option value="766" >Wantirna South</option>
        <option value="767" >Warburton</option>
        <option value="1048" >Warburton East</option>
        <option value="768" >Warneet</option>
        <option value="1071" >Warragul</option>
        <option value="769" >Warrandyte</option>
        <option value="770" >Warrandyte South</option>
        <option value="771" >Warranwood</option>
        <option value="772" >Waterways</option>
        <option value="773" >Watsonia</option>
        <option value="774" >Watsonia North</option>
        <option value="775" >Watsons Creek</option>
        <option value="776" >Wattle Bank</option>
        <option value="777" >Wattle Glen</option>
        <option value="778" >Waurn Ponds</option>
        <option value="779" >Wensleydale</option>
        <option value="780" >Werribee</option>
        <option value="781" >Werribee South</option>
        <option value="782" >Wesburn</option>
        <option value="783" >West Creek</option>
        <option value="784" >West Footscray</option>
        <option value="785" >West Melbourne</option>
        <option value="787" >Westmeadows</option>
        <option value="1074" >Wheatsheaf</option>
        <option value="788" >Wheelers Hill</option>
        <option value="789" >Whitelaw</option>
        <option value="790" >Whittington</option>
        <option value="791" >Whittlesea</option>
        <option value="792" >Wildwood</option>
        <option value="793" >Williams Landing</option>
        <option value="794" >Williamstown</option>
        <option value="795" >Williamstown North</option>
        <option value="796" >Wimbledon Heights</option>
        <option value="797" >Winchelsea</option>
        <option value="798" >Winchelsea South</option>
        <option value="799" >Windsor</option>
        <option value="800" >Wollert</option>
        <option value="801" >Wonga Park</option>
        <option value="802" >Wonthaggi</option>
        <option value="803" >Woodend</option>
        <option value="804" >Woodleigh</option>
        <option value="806" >Woodstock</option>
        <option value="807" >Woolamai</option>
        <option value="808" >Woori Yallock</option>
        <option value="810" >Wurdiboluc</option>
        <option value="811" >Wyndham Vale</option>
        <option value="812" >Yallambie</option>
        <option value="814" >Yan Yean</option>
        <option value="815" >Yannathan</option>
        <option value="816" >Yarra Glen</option>
        <option value="817" >Yarra Junction</option>
        <option value="818" >Yarrambat</option>
        <option value="819" >Yarraville</option>
        <option value="820" >Yellingbo</option>
        <option value="821" >Yering</option>
        <option value="822" >Yuroke</option>
      </select>
      <input type="hidden" name="dSuburb" id="text_content1" value="" />
          </div>
        </div>
        <div class="row last">
          
          <div class="form-group col-sm-6" >
             <textarea name ="notes" placeholder="Note for driver (OPTIONAL)" style = "width:100%" class="form-control"></textarea>
          </div>
          <div class="form-group col-sm-offset-1 col-sm-5"  >
            <button type="Submit" style="width:150px;float:right" class="btn btn-success">Book Now!!</button>  
          </div>
        </div>
      </div>
    </form>
    <div class="col-sm-4 imag"></div>
    </div> 
    
  </div>
      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript">
      $("#tip").tooltip();
     
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        
    </script>
    <?php
      unset($_SESSION['name']);
      unset($_SESSION['email']);
      unset($_SESSION['phone']);
      unset($_SESSION['date']);
      unset($_SESSION['time']);
      unset($_SESSION['car']);
      unset($_SESSION['pAddress']);
      unset($_SESSION['pUnit']);
      unset($_SESSION['pSuburb']);
      unset($_SESSION['dUnit']);
      unset($_SESSION['dAddress']);
      unset($_SESSION['dSuburb']);
    ?>
     </body>
     </html>